GET http://localhost:3001/api/members

###
POST http://localhost:3001/api/auth/user
content-type: application/json

{"username": "Pedro",
    "password": "abc123",
    "fullname": "Pedro García González",
    "email": "franzz2000@mail.com",
    "role": "admin"
 }

### Crear un miembro
POST http://localhost:3001/api/members/
content-type: application/json

 {"name": "Pedro",
    "surname": "Jimeno Demuth",
    "jobTitle": "Traumatología",
    "phone": "656473937",
    "email": "franzz2000@mail.com",
    "identifier": "37333513M",
    "comment": "Esto es un comentario"
 }

###
POST http://localhost:3001/api/members/
content-type: application/json

 {"name": "Javier",
    "surname": "González Fernández",
    "jobTitle": "Enfermero",
    "phone": "656473933",
    "email": "franz112000@gmail.com",
    "identifier": "37333514M",
    "comment": "Esto es un segundo comentario"
 }

### Recuperar un miembro
# Incluir un id correcto
GET http://localhost:3001/api/members/66b98308ed75a37bf68a0432

### 
PUT http://localhost:3001/api/members/66b98308ed75a37bf68a0432
Content-Type: application/json

{"name": "Juan"}

###
DELETE http://localhost:3001/api/members/66b5e5c29321731ca5631854

###
GET http://localhost:3001/api/groups

###

POST http://localhost:3001/api/groups
Content-Type: application/json

{
  "name": "Comité de sarcoma",
  "tipo1": "Comité",
  "tipo2": "Calidad",
  "constitutionDate": "2024-11-05",
  "members": [
    {"_id": "66b98308ed75a37bf68a0432",
    "role": "Miembro",
    "startDate": "2024-11-06"}
  ]
}

###

GET http://localhost:3001/api/groups/members/66b983c5ed75a37bf68a0437